[package]
name = "nails-fork"
version = "0.2.0"
authors = ["Stu Hood <stuhood@gmail.com>"]
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/stuhood/nails"
homepage = "https://github.com/stuhood/nails"
description = """
A `Nail` trait implementation that forks a process as the user running the server.
"""

[dependencies]
nails = { path = "../nails", version = "=0.2.0" }
bytes = "0.4"
futures = "0.1"
tokio-codec = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-process = "0.1"
