[package]
name = "nails-client"
version = "0.1.0"
authors = ["Stu Hood <stuhood@gmail.com>"]

[dependencies]
env_logger = "0.5.4"
futures = "0.1"
log = "0.4"
nails = { path = "../nails" }
tokio-core = "0.1"
